version: '3.8'
services:
  backend:
    build: 
      context: ./backend/src/backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - r4d4-network
    ports:
      - "5000:5000"
    env_file: ./backend/src/backend/.env
    restart: always
    command: ["dotnet", "backend.dll", "--urls", "http://0.0.0.0:5000"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - r4d4-network
    ports:
      - "8080:8080"
    restart: always
    command: ["nginx", "-g", "daemon off;"]

networks:
  r4d4-network:
    driver: bridge
